[package]
name = "substrate-runtime-interface"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
wasm-interface = { package = "substrate-wasm-interface", path = "../wasm-interface", optional = true }
rstd = { package = "sr-std", path = "../sr-std", default-features = false }
primitives = { package = "substrate-primitives", path = "../primitives", default-features = false }
substrate-runtime-interface-proc-macro = { path = "proc-macro" }
codec = { package = "parity-scale-codec", version = "1.0.5", default-features = false }

[dev-dependencies]
executor = { package = "substrate-executor", path = "../executor" }
test-wasm = { package = "substrate-runtime-interface-test-wasm", path = "test-wasm" }
state_machine = { package = "substrate-state-machine", path = "../state-machine"  }

[features]
default = [ "std" ]
std = [ "wasm-interface", "rstd/std", "codec/std", "primitives/std" ]
